config/routes.rb
Rails.application.routes.draw do
  root 'articles#index'

  resources :articles

  resources :users, only: [:new, :create, :show]

  resources :categories, only: [:show]

  resources :votes, only: [:show, :create, :destroy]
  
  resources :sessions, only: [:new, :create, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  attr_accessor :category_id

  mount_uploader :image, ImageUploader

  belongs_to :author, class_name: 'User'

  has_and_belongs_to_many :categories

  has_many :votes, dependent: :destroy

  validates :title, :text, :image, presence: true

  def self.no_articles_img
    'https://res.cloudinary.com/strawberry-cloud/image/upload/v1597782927/joe-woods-4Zaq5xY5M_c-unsplash_mjekpx.png'
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_and_belongs_to_many :articles
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  has_many :votes
  has_many :articles, foreign_key: 'author_id'
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_variables, only: %i[show edit update destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show; end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
    @user = User.find(session[:current_user])
    @article = @user.articles.find(params[:id])
  end

  # POST /articles
  # POST /articles.json
  def create
    @user = User.find(session[:current_user])
    @article = @user.articles.build(article_params)

    respond_to do |format|
      if @article.save
        @article.categories << Category.find(article_params[:category_id])
        format.html do
          redirect_to category_path(article_params[:category_id]),
                      notice: 'Article was successfully created.'
        end
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        @article.categories.destroy_all
        @article.categories << Category.find(article_params[:category_id])
        format.html do
          redirect_to category_path(article_params[:category_id]),
                      notice: 'Article was successfully updated.'
        end
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to request.referrer, notice: 'Article was successfully destroyed.' }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_variables
    @article = Article.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def article_params
    params.require(:article).permit(:title, :text, :image, :category_id)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.find(params[:id])
    @articles = Category.find(params[:id]).articles
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(name: params[:name])
    if user
      session[:current_user] = user.id
      redirect_to articles_path
    else
      flash[:alert] = 'There is no user with that name'
      render :new
    end
  end

  def destroy
    session[:current_user] = nil
    redirect_to articles_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "User with name #{@user.name} successfully created"
      redirect_to articles_path
      session[:current_user] = @user.id
    else
      flash[:alert] = "User couldn't be created"
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:name)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def index
    @votes = Vote.all
  end

  def create
    User.find(session[:current_user]).votes.create(vote_params)
    redirect_to request.referrer
  end

  def destroy
    Vote.find(params[:id]).destroy
    redirect_to request.referrer
  end

  private

  def vote_params
    params.require(:votes).permit(:author_id, :article_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def auth_links
    if session[:current_user]
      render '/layouts/username_log_out'
    else
      render '/layouts/sign_in_sign_up'
    end
  end

  def check_notice(notice)
    render '/layouts/notice', msg: notice if notice
  end

  def no_category_msg
    render '/layouts/run_seed_pls' if Category.all.size.zero?
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def featured_article
    Article.includes(:votes).all.max { |a, b| a.votes.count <=> b.votes.count }
  end

  def featured_img
    if featured_article
      featured_article.image
    else
      Article.no_articles_img
    end
  end

  def featured_title
    if featured_article
      featured_article.title
    else
      'No Featured Posts So Far'
    end
  end

  def featured_id
    featured_article&.id
  end

  def edit_btn(article)
    render 'articles/edit_button', article: article if article.author_id == session[:current_user]
  end

  def delete_btn(article)
    render 'articles/delete_button', article: article if article.author_id == session[:current_user]
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
  def category_last(category)
    category.articles.last if category.articles.exists?
  end

  def category_last_img(category)
    if category_last(category)
      category_last(category).image
    else
      Article.no_articles_img
    end
  end

  def category_last_title(category)
    if category_last(category)
      category_last(category).title
    else
      'This Category Has No Posts'
    end
  end

  def category_last_id(category)
    category_last(category)&.id
  end

  def category_link(category)
    category_path(category.id) if category_last(category)
  end
end

app/helpers/votes_helper.rb
module VotesHelper
  def vote_btn(article)
    return nil if session[:current_user].nil?

    user = User.find(session[:current_user])
    vote = user.votes.where(user_id: user.id, article_id: article.id).take
    if vote
      link_to 'Take Vote', vote_path(vote.id), method: 'delete', class: 'btn btn-warning btn-small'
    else
      link_to 'Vote', votes_path(user, votes: { user_id: user.id, article_id: article.id }),
              method: 'post', class: 'btn btn-primary btn-small'
    end
  end

  def votes_text(votes)
    if votes.zero?
      nil
    elsif votes == 1
      '1 vote'
    else
      votes.to_s + ' votes'
    end
  end
end

app/views/articles/_delete_button.html.erb
<%= link_to article_path(article.id), {method: 'delete', data: {confirm: "Are you sure you want to delete the article?"}, class: 'ml-2 text-danger'} do%>
  Delete
  <i class="far fa-trash-alt"></i>
<% end %>

app/views/articles/_edit_button.html.erb
<%= link_to edit_article_path(article.id), class: 'ml-2' do%>
  Edit
  <i class="far fa-edit"></i>
<% end %>

app/views/articles/_form.html.erb
<div class="d-flex align-items-start">
  <%= form_with(model: article, local: true) do |form| %>
    <% if article.errors.any? %>
      <div id="error_explanation">
  
        <ul>
          <% article.errors.full_messages.each do |message| %>
            <li class="text-danger"><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="form-group">
      <%= form.label :category_id %>
      <%= form.collection_select(:category_id, Category.all, :id, :name, { promt: 'Please select the category of the meal'}, { class: 'form-control' })%>
    </div>
  
    <div class="form-group">
      <%= form.label :title %>
      <%= form.text_field :title, class: 'form-control'%>
    </div>
  
    <div class="form-group">
      <%= form.label :text %>
      <%= form.text_area :text, class: 'form-control' %>
    </div>
  
    <div class="form-group">
      <%= form.label :image %>
      <%= form.file_field :image, class: 'form-control-file' %>
    </div>
  
    <div class="actions">
      <button type="submit" class="btn btn-success btn-block mb-2">Publish</button>
    </div>
  <% end %>
</div>

app/views/articles/edit.html.erb
<div class="flex-center flex-column text-white py-4">
  <h1>Editing Recipe</h1>

  <%= render 'form', article: @article %>

  <%= link_to 'Back', articles_path %>
</div>

app/views/articles/index.html.erb
<%= check_notice(flash[:success]) %>
  
<div class="main-grid">

  <div class="featured" style= "background: #ffffff url(<%= featured_img %>) no-repeat center center/cover" >
    <a href=<%= articles_path(featured_id) %> class="featured-link"></a>
    <span class="featured-title font-chivo"><%= featured_title %></span>
  </div>

  
  <% Category.includes(:articles).all.order(priority: 'DESC').each do |category| %>
    <% img_url = category_last_img(category) %>
    <div class="category" style="background: #ffffff url(<%=img_url%>) no-repeat center / cover">
      <a href=<%= category_link(category) %> class="category-link"></a>
      <span class="category-name font-chivo text-white"><%= category.name %></span>
      <a class="category-last-article font-chivo text-white"><%= category_last_title(category) %></a>
    </div>
  <% end %>

</div>

app/views/articles/new.html.erb
<div class="flex-center flex-column text-white py-4">
  <h1>New Recipe</h1>
  <%= render 'form', article: @article %>
  <%= link_to 'Back', articles_path %>
</div>

app/views/categories/show.html.erb
<%= check_notice(notice) %>

<div class="category-container font-chivo">
  
  <% _offset = 0 %>
              
  <% while _offset < @articles.count %>

    <% @articles.includes(:votes).order(id: 'DESC').limit(2).offset(_offset).find_each do |article| %>
      
      <div class="cat-article-img" style="background: url(<%= article.image %>) no-repeat center / cover"></div>
      
      <div class="cat-article-cont">
        <h2 class="cat-name text-orange mr-5"><%= @category.name %></h2>
        <br>
        <h3 class="cat-article-name d-inline-block"><%= article.title %></h3>
        <p class="cat-article-text"><%= article.text %></p>
        <span><%= votes_text(article.votes.count) %></span>
        <%= vote_btn(article) %>
        <span class="article-actions">
          <%= edit_btn(article) %>
          <%= delete_btn(article) %>
        </span>
      </div>

      <% _offset += 1 %>

    <% end %>

    <% @articles.order(id: 'DESC').limit(2).offset(_offset).find_each do |article| %>
      <% break if _offset >= @articles.size %>
      <div class="cat-article-cont ">
        <h2 class="cat-name text-orange mr-5"><%= @category.name %></h2>
        <br>
        <h3 class="cat-article-name d-inline-block"><%= article.title %></h3>
        
        <p class="cat-article-text"><%= article.text %></p>
        <span><%= votes_text(article.votes.count) %></span>
        <%= vote_btn(article) %>
        <span class="article-actions">
          <%= edit_btn(article) %>
          <%= delete_btn(article) %>
        </span>
      </div>

      <div class="cat-article-img" style="background: url(<%= article.image %>) no-repeat center / cover"></div>
      
      <% _offset += 1 %>

    <% end %>

  <% end %>
</div>

app/views/layouts/_notice.html.erb
<div class="alert alert-info text-center p-1 rounded-0 mb-0">
    <%= msg %>
    <button type="button" class="close" data-dismiss="alert">
      <span aria-hidden="true">×</span>
      <span class="sr-only">Close</span>
    </button>
</div>

app/views/layouts/_run_seed_pls.html.erb
<div class="alert alert-danger text-center p-1 rounded-0 mb-0">
    <p>There are no categories in database. Please run <code>rails db:seed</code> first</p>
</div>

app/views/layouts/_sign_in_sign_up.html.erb
<div class='d-flex align-items-center'>
    <%= link_to "Sign in", new_session_path, class: 'nav-item nav-link text-uppercase' %>
    <%= link_to "Sign up", new_user_path, class: 'nav-item nav-link text-uppercase' %>
</div>

app/views/layouts/_username_log_out.html.erb
<div class='d-flex align-items-center font-lato'>
    <a href=<%= new_article_path %>>
      <button class="btn btn-success btn-sm mr-5">Add New Recipe</button>
    </a>
    <%= link_to User.find(session[:current_user]).name, user_path(session[:current_user]), class: 'user-name' %>
    <%= link_to "SIGN OUT", session_path(session[:current_user]), :method => :delete, class: 'nav-link' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Big Strawberry</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="description" content="_" />
    <meta name="title" property="og:title" content="Big Strawberry" />
    <meta property="og:type" content="Website" />
    <meta name="image" property="og:image" content="https://raw.githubusercontent.com/8Bts/Big_Strawberry/develop/app/assets/images/screenshot.png" />
    <meta name="description" property="og:description" content="Full-stack Rails application for cooking recipes. Built with Ruby on Rails, Bootstrap, PostgreSQL, RSpec." />
    <meta name="author" content="Rashid Mammadli (@8Bts)" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/e2597287a1.js" crossorigin="anonymous"></script>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </head>

  <body>
    <div class="page-container">
      <nav class="navbar navbar-expand navbar-light bg-white d-flex justify-content-between">
        <div class="logo-nav">
        	<a href= <%= root_path %> class="nav-link">
            <span class="logo-text text-orange">
            BigStrawberry
            </span>
          </a>
        </div>
  
        <div class="nav-middle">
          <%= no_category_msg %>
          <% Category.all.each do |category| %>
            <%= link_to category.name, category_path(category.id), class: 'font-red-rose nav-middle-link' %>
          <% end %>
        </div>
        
        <div class="navbar-nav d-flex justify-content-end">
          <a class="nav-item nav-link active" href="#"> <span class="sr-only">(current)</span></a>
          <%= auth_links %>
        </div>
        
      </nav>
  
      <main class="bg-second">
        <div class="main-container">
          <%= yield %>
        </div>
      </main>
  
      <footer>
  
        <div class="footer d-flex justify-content-between font-lato">
          <div class="logo-nav">
        	  <a href= <%= root_path %> class="nav-link">
              <span class="logo-text text-orange">
              BigStrawberry
              </span>
            </a>
          </div>
  
          <div class="footer-mid py-3 font-small">
            <a href="#" class="text-orange">Privacy Policy  Terms & Conditions</a>
            <a href="#" class="text-white">Copyright 2020, All Rights Reserved</a>
          </div>
  
          <div class="footer-end font-small p-3">
            <span class="text-white">Connect with us:</span>
            <a href="#">
              <i class="fab fa-twitter fa-lg text-orange"></i>
            </a>
            <a href="#">
            <i class="fab fa-instagram fa-lg text-orange"></i>          
            </a>
            <a href="#">
            <i class="fab fa-facebook fa-lg text-orange"></i>
            </a>
          </div>
        </div>
  
      </footer>
    </div>
  </body>
</html>

app/views/users/new.html.erb
<div class="flex-center mt-5 form-group">

  <%= form_for @user do |f| %>
  <% if @user.errors.any? %>
      <div id="error_explanation">
  
        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li class="text-danger"><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  <%= f.label :name, 'Username', class: 'text-white'%>
  <%= f.text_field :name, class: 'form-control'%>
  <button type="submit" class="btn bg-success btn-block mt-2">Sign Up</button>
  <% end %>
</div>

app/views/users/show.html.erb
<%= check_notice(notice) %>

<div class="user-show-page font-chivo bg-light py-5">
  <ul class="list-group ml-5">
  <h2 class="text-black-50">My Recipies</h2>
  <% if @user.articles.exists?%>
    <% @user.articles.find_each do |article| %>
  
    <li class="list-group-item">
      <div class="user-art-cont mb-3 row">
        <div class="user-art-left col-2" style="background: url(<%= article.image %>) center / cover"></div>
        <div class="user-art-right col-10">
          <h3 class="user-art-title d-inline-block"> <%= article.title %> </h3>
          <%= edit_btn(article) %>
          <%= delete_btn(article) %>
          <p class="user-art"> <%= article.text %> </p>   
        </div>
      </div>
    </li>
  
    <% end %>
  <% else %>
    <p class='user-no-recipies'>You don't have any recipies so far</p>
  <% end %>
  </ul>
</div>

app/views/votes/index.html.erb
<%= @votes.each do |vote| %>
    <div>
        <% vote.user.name %>
    </div>
<% end %>